[circuit_synthesizer]
generation_timeout_in_secs=3000
max_attempts=3
gpu_prover_queue_timeout_in_secs=600
prover_instance_wait_timeout_in_secs=200
prover_instance_poll_time_in_milli_secs=250
prometheus_listener_port=3314
prometheus_pushgateway_url="http://127.0.0.1:9091"
prometheus_push_interval_ms=100
prover_group_id=100
