[prover_group]
group_0_circuit_ids="0,18"
group_1_circuit_ids="1,4"
group_2_circuit_ids="2,5"
group_3_circuit_ids="6,7"
group_4_circuit_ids="8,9"
group_5_circuit_ids="10,11"
group_6_circuit_ids="12,13"
group_7_circuit_ids="14,15"
group_8_circuit_ids="16,17"
group_9_circuit_ids="3"
group_100_circuit_ids=""
region_read_url="http://metadata.google.internal/computeMetadata/v1/instance/attributes/cluster-location"
region_override="us-central-1"
zone_read_url="http://metadata.google.internal/computeMetadata/v1/instance/zone"
zone_override="us-central-1-b"
synthesizer_per_gpu="10"
